export const TIMEZONE_OPTIONS = [
  { label: "UTC", value: "UTC" },
  // Americas
  { label: "America/New_York", value: "America/New_York" },
  { label: "America/Chicago", value: "America/Chicago" },
  { label: "America/Denver", value: "America/Denver" },
  { label: "America/Los_Angeles", value: "America/Los_Angeles" },
  { label: "America/Phoenix", value: "America/Phoenix" },
  { label: "America/Anchorage", value: "America/Anchorage" },
  { label: "America/Honolulu", value: "America/Honolulu" },
  { label: "America/Toronto", value: "America/Toronto" },
  { label: "America/Vancouver", value: "America/Vancouver" },
  { label: "America/Mexico_City", value: "America/Mexico_City" },
  { label: "America/Bogota", value: "America/Bogota" },
  { label: "America/Lima", value: "America/Lima" },
  { label: "America/Santiago", value: "America/Santiago" },
  { label: "America/Sao_Paulo", value: "America/Sao_Paulo" },
  {
    label: "America/Argentina/Buenos_Aires",
    value: "America/Argentina/Buenos_Aires",
  },
  { label: "America/Halifax", value: "America/Halifax" },
  // Europe
  { label: "Europe/London", value: "Europe/London" },
  { label: "Europe/Dublin", value: "Europe/Dublin" },
  { label: "Europe/Lisbon", value: "Europe/Lisbon" },
  { label: "Europe/Paris", value: "Europe/Paris" },
  { label: "Europe/Berlin", value: "Europe/Berlin" },
  { label: "Europe/Rome", value: "Europe/Rome" },
  { label: "Europe/Madrid", value: "Europe/Madrid" },
  { label: "Europe/Amsterdam", value: "Europe/Amsterdam" },
  { label: "Europe/Brussels", value: "Europe/Brussels" },
  { label: "Europe/Zurich", value: "Europe/Zurich" },
  { label: "Europe/Stockholm", value: "Europe/Stockholm" },
  { label: "Europe/Vienna", value: "Europe/Vienna" },
  { label: "Europe/Warsaw", value: "Europe/Warsaw" },
  { label: "Europe/Prague", value: "Europe/Prague" },
  { label: "Europe/Helsinki", value: "Europe/Helsinki" },
  { label: "Europe/Bucharest", value: "Europe/Bucharest" },
  { label: "Europe/Athens", value: "Europe/Athens" },
  { label: "Europe/Istanbul", value: "Europe/Istanbul" },
  { label: "Europe/Moscow", value: "Europe/Moscow" },
  { label: "Europe/Kyiv", value: "Europe/Kyiv" },
  // Africa
  { label: "Africa/Cairo", value: "Africa/Cairo" },
  { label: "Africa/Lagos", value: "Africa/Lagos" },
  { label: "Africa/Johannesburg", value: "Africa/Johannesburg" },
  { label: "Africa/Nairobi", value: "Africa/Nairobi" },
  { label: "Africa/Casablanca", value: "Africa/Casablanca" },
  // Middle East & Asia
  { label: "Asia/Jerusalem", value: "Asia/Jerusalem" },
  { label: "Asia/Riyadh", value: "Asia/Riyadh" },
  { label: "Asia/Dubai", value: "Asia/Dubai" },
  { label: "Asia/Tehran", value: "Asia/Tehran" },
  { label: "Asia/Karachi", value: "Asia/Karachi" },
  { label: "Asia/Kolkata", value: "Asia/Kolkata" },
  { label: "Asia/Dhaka", value: "Asia/Dhaka" },
  { label: "Asia/Bangkok", value: "Asia/Bangkok" },
  { label: "Asia/Jakarta", value: "Asia/Jakarta" },
  { label: "Asia/Ho_Chi_Minh", value: "Asia/Ho_Chi_Minh" },
  { label: "Asia/Singapore", value: "Asia/Singapore" },
  { label: "Asia/Manila", value: "Asia/Manila" },
  { label: "Asia/Shanghai", value: "Asia/Shanghai" },
  { label: "Asia/Hong_Kong", value: "Asia/Hong_Kong" },
  { label: "Asia/Taipei", value: "Asia/Taipei" },
  { label: "Asia/Seoul", value: "Asia/Seoul" },
  { label: "Asia/Tokyo", value: "Asia/Tokyo" },
  // Australia & Pacific
  { label: "Australia/Perth", value: "Australia/Perth" },
  { label: "Australia/Adelaide", value: "Australia/Adelaide" },
  { label: "Australia/Brisbane", value: "Australia/Brisbane" },
  { label: "Australia/Sydney", value: "Australia/Sydney" },
  { label: "Australia/Melbourne", value: "Australia/Melbourne" },
  { label: "Pacific/Auckland", value: "Pacific/Auckland" },
  { label: "Pacific/Fiji", value: "Pacific/Fiji" },
  { label: "Pacific/Guam", value: "Pacific/Guam" },
];

export const REGION_OPTIONS = [
  { label: "None", value: "none" },
  { label: "US East", value: "us-east" },
  { label: "US West", value: "us-west" },
  { label: "EU West", value: "eu-west" },
  { label: "EU Central", value: "eu-central" },
  { label: "Asia Pacific Southeast", value: "ap-southeast" },
  { label: "Asia Pacific Northeast", value: "ap-northeast" },
];

export const TIMEZONE_TO_REGION = {
  UTC: "none",
  // Americas
  "America/New_York": "us-east",
  "America/Chicago": "us-east",
  "America/Denver": "us-west",
  "America/Los_Angeles": "us-west",
  "America/Phoenix": "us-west",
  "America/Anchorage": "us-west",
  "America/Honolulu": "us-west",
  "America/Toronto": "us-east",
  "America/Vancouver": "us-west",
  "America/Mexico_City": "us-east",
  "America/Bogota": "us-east",
  "America/Lima": "us-east",
  "America/Santiago": "us-east",
  "America/Sao_Paulo": "us-east",
  "America/Argentina/Buenos_Aires": "us-east",
  "America/Halifax": "us-east",
  // Europe
  "Europe/London": "eu-west",
  "Europe/Dublin": "eu-west",
  "Europe/Lisbon": "eu-west",
  "Europe/Paris": "eu-west",
  "Europe/Berlin": "eu-central",
  "Europe/Rome": "eu-central",
  "Europe/Madrid": "eu-west",
  "Europe/Amsterdam": "eu-west",
  "Europe/Brussels": "eu-west",
  "Europe/Zurich": "eu-central",
  "Europe/Stockholm": "eu-central",
  "Europe/Vienna": "eu-central",
  "Europe/Warsaw": "eu-central",
  "Europe/Prague": "eu-central",
  "Europe/Helsinki": "eu-central",
  "Europe/Bucharest": "eu-central",
  "Europe/Athens": "eu-central",
  "Europe/Istanbul": "eu-central",
  "Europe/Moscow": "eu-central",
  "Europe/Kyiv": "eu-central",
  // Africa
  "Africa/Cairo": "eu-central",
  "Africa/Lagos": "eu-west",
  "Africa/Johannesburg": "eu-central",
  "Africa/Nairobi": "eu-central",
  "Africa/Casablanca": "eu-west",
  // Middle East & Asia
  "Asia/Jerusalem": "eu-central",
  "Asia/Riyadh": "ap-southeast",
  "Asia/Dubai": "ap-southeast",
  "Asia/Tehran": "ap-southeast",
  "Asia/Karachi": "ap-southeast",
  "Asia/Kolkata": "ap-southeast",
  "Asia/Dhaka": "ap-southeast",
  "Asia/Bangkok": "ap-southeast",
  "Asia/Jakarta": "ap-southeast",
  "Asia/Ho_Chi_Minh": "ap-southeast",
  "Asia/Singapore": "ap-southeast",
  "Asia/Manila": "ap-southeast",
  "Asia/Shanghai": "ap-northeast",
  "Asia/Hong_Kong": "ap-southeast",
  "Asia/Taipei": "ap-northeast",
  "Asia/Seoul": "ap-northeast",
  "Asia/Tokyo": "ap-northeast",
  // Australia & Pacific
  "Australia/Perth": "ap-southeast",
  "Australia/Adelaide": "ap-southeast",
  "Australia/Brisbane": "ap-southeast",
  "Australia/Sydney": "ap-southeast",
  "Australia/Melbourne": "ap-southeast",
  "Pacific/Auckland": "ap-southeast",
  "Pacific/Fiji": "ap-southeast",
  "Pacific/Guam": "ap-southeast",
};
